### ISSUE TITLE
Add Menu page design Enhancement

### ISSUE THREAD

**Issue by Priyanshu9898** [SE-Fall24-G73/86-No-More#2]
Add Menu page design Enhancement

form should be on center, responsive design

**Comment by Priyanshu9898** [comment]
![image](https://github.com/user-attachments/assets/699a0356-8259-4d06-ae1a-a13b2fa5e16b)

refer this @VaishviShah

**Comment by VaishviShah** [comment]
![image](https://github.com/user-attachments/assets/027c2d8e-e2e9-4e71-9ce9-44cc6783aee5)
![image](https://github.com/user-attachments/assets/6e2d21ec-6c77-435a-be3f-db698580a64c)

updated the menu page

**Comment by VaishviShah** [comment]
![image](https://github.com/user-attachments/assets/8693a8d4-7b8d-4a22-a59b-32558f4397dd)
enhanced the cart page as well.

![image](https://github.com/user-attachments/assets/219e313d-268a-486f-8fc1-d715a3679651)
enhanced and made predict page responsive.
