### ISSUE TITLE
Navbar design Enhancement

### ISSUE THREAD

**Issue by Priyanshu9898** [SE-Fall24-G73/86-No-More#5]
Navbar design Enhancement, make it responsive and better design

**Comment by abhandary14** [comment]
![WhatsApp Image 2024-11-20 at 18 05 51_b2f83030](https://github.com/user-attachments/assets/d9f3ebbb-47b2-490f-9ff6-29637a24caaf)

Clicking on the highlighted (gray arrow) doesn't work for any icon. User has to click on the icon (green arrow). Please fix it. Could be a small but nice UX enhancement.

**Comment by VaishviShah** [comment]
Okay, got it!

**Comment by VaishviShah** [comment]
![image](https://github.com/user-attachments/assets/239a2af9-0c49-4d1e-8d63-a10c0dd252c2)
Completed Login page responsiveness

**Comment by VaishviShah** [comment]
![image](https://github.com/user-attachments/assets/61a6da28-5d6a-466b-b65b-23678cb60f00)
![image](https://github.com/user-attachments/assets/4ab1c057-9d79-4663-b665-df21496212a8)
![image](https://github.com/user-attachments/assets/d9f1a947-42cb-4c83-8c93-8b8d7b080055)
![image](https://github.com/user-attachments/assets/20346a25-794e-495c-acf0-36c811eb29d1)
Completed Navigation Bar Responsiveness across all pages

**Comment by VaishviShah** [comment]
![image](https://github.com/user-attachments/assets/29c79a3e-ac88-42ad-a08c-951a18be5f91)
Enhanced home page as well
